name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.idea/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Verify Docker is running
      run: docker info

    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build and test with Gradle
      run: ./gradlew build

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          **/build/reports/tests/
          **/build/test-results/
